[workspace]
resolver = "2"
members = [
    "libsubid",
    "libsubid-dylib",
]

[workspace.package]
authors = ["Tomer Hanochi <crates.io@tomerhanochi.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/tomerhanochi/libsubid"
rust-version = "1.83"
version = "0.2.0"
