[package]
name = "libsubid-dylib"
version = "0.0.4"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libsubid = { path = "../libsubid", features = ["mock"] }
libc = "0.2"

[features]
mock = ["libsubid/mock"]
