[package]
name = "libsubid-dylib"
version = "0.0.6"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libsubid = { path = "../libsubid" }
libc = "0.2"

[features]
mock-subuid = []
mock-subgid = []
dynamic-subuid = []
dynamic-subgid = []
